### ISSUE TITLE
前台修改 ''权限管理'' 会导致父模块undefined

### ISSUE THREAD

**Issue by 6kun** [xjchenhao/egg-admin-service#2]
功能模块管理》模块Url   不太明白用途，是权限标识uri吗？是否可以加个模糊搜索，模块名称那里。

前台修改 ''权限管理'' 会导致父模块undefined，小白水平不够搞不定,只能MongoDB后台改  parent_id": "" ,希望可以修复一下.

**Comment by xjchenhao** [comment]
你好 模块uri是service的router.js中，中间件别名关联的(如下图)。录入的时候需要开发 人工一一对应一下。
![image](https://user-images.githubusercontent.com/5373111/41267582-8bde6680-6e2e-11e8-83dc-95723a42f714.png)

ps：模糊搜索我考虑过，但是怕使用过程中误操作，选错了权限标识。
