### ISSUE TITLE
左侧菜单不显示

### ISSUE THREAD

**Issue by 6kun** [xjchenhao/egg-admin-service#3]
umi.js:52597 ./src/common/menu.js
  Line 23:  'menuData' is assigned a value but never used  no-unused-vars
printWarnings @ umi.js:52597
umi.js:52597 ./src/pages/sys/user/register.js
  Line 23:  componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops  react/no-deprecated
printWarnings @ umi.js:52597
umi.js:52597 ./src/layouts/UserLayout.js
  Line 2:   'Redirect' is defined but never used           no-unused-vars
  Line 2:   'Switch' is defined but never used             no-unused-vars
  Line 2:   'Route' is defined but never used              no-unused-vars
  Line 29:  'pathname' is assigned a value but never used  no-unused-vars
printWarnings @ umi.js:52597
umi.js:52597 ./src/models/sys/login.js
  Line 2:  'router' is defined but never used  no-unused-vars
printWarnings @ umi.js:52597
umi.js:52597 ./src/components/SiderMenu/SiderMenu.js
  Line 32:  componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops  react/no-deprecated
printWarnings @ umi.js:52597
umi.js:52593 There were more warnings in other files.
You can find a complete log in the terminal.

**Comment by xjchenhao** [comment]
不好意思最近不稳定，在基于umi做重构(改成侧栏通过服务端的api显示结果)，现在可以显示了，但是初次加载的时候还有点问题。

**建议先拉`antd-pro`分支**

**Comment by xjchenhao** [comment]
被你猜对了，是数据库结构改过了，我晚点上传一个`init.sh`上去。

> 就不该把开发中的推到主分支去 😂
> `antd-pro`分支还是能用的哦

**Comment by xjchenhao** [comment]
我上传了新的`initAuth.js`，你删除掉`groups`、`modules`、`users`这三个数据集合。
到`/service/init.d/mongo`文件夹执行`sudo ./init.sh`看看。

https://github.com/xjchenhao/egg-admin-service/commit/140d3a526b5b656a6cfa32cf7b34540b19005499
