### ISSUE TITLE
新的生命周期: getDerivedStateFromProps

### ISSUE THREAD

**Issue by 6kun** [xjchenhao/egg-admin-service#4]
虽然不影响使用,不过还是改了更舒心,呵呵.
https://github.com/liuxx001/bird-front
里的按钮渲染权限控制有没兴趣加上

**Comment by xjchenhao** [comment]
`getDerivedStateFromProps`已经改了哦。

https://github.com/xjchenhao/egg-admin-service/commit/53b7bd93f31fc51453630674e70e93023bde5c31
